name: issue_workflow
on:
  issues:
    types: [opened]

jobs:
  issue-job:
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github action